Repository UKHomeOffice/hocs-migration-schema, pull requests merged in 2022-08, with the labels that each got.

#5 HOCS-5386: Flatten DECS migration schema.
  src/main/resources/hocs-migration-schema.json
  src/test/java/uk/gov/digital/ho/hocs/migration/JSONValidate.java
  src/test/resources/jsonMigrationExamples/cms.json
  src/test/resources/jsonMigrationExamples/invalid-case-data.json
Labels: minor

#6 ⬆️ Repoint GH actions to new repo
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
Labels: skip-release

#7 ✨ HOCS-5511: Add maven publish tag and branch jobs
  .drone.yml
  .github/workflows/maven-publish-branch.yml
  .github/workflows/maven-publish-tag.yml
  .github/workflows/pr-check.yml
  .github/workflows/semver.yml
  .github/workflows/test.yml
Labels: skip-release, smoketest
